### ISSUE TITLE
La doc est erronée

### ISSUE THREAD

**Issue by benjello** [fpagnoux/baremes-ipp-views#2]
La doc expliquant la configuration du répertoire tables devrait plutôt se trouver dans le repo où [le répertoire réside désormais](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml).

**Comment by fpagnoux** [comment]
J'ai ajouté[ un morceau de doc](https://framagit.org/french-tax-and-benefit-tables/baremes-ipp-yaml/blob/master/tables/README.md) avec un lien sur le répertoire qui contient les YAML.
Pour la maintenance du générateur de vue, je pense que c'est pas mal de garder la doc à proximité du code.
